### ISSUE TITLE
-v not working for unixclient?

### ISSUE THREAD

**Issue by tfarina** [bruceg/ucspi-unix#1]
If I run unixclient like the following, then connect fails:

$ ./unixclient -v ~/ucspi-unix-1.0/server.socket ls
connect: No such file or directory

If I run without -v flag, then it works:
$ ./unixclient -v ~/ucspi-unix-1.0/server.socket ls
...

**Comment by bruceg** [comment]
I'm not sure why those option descriptions were left in unixclient. It doesn't actually parse options, nor does it have any points where it could print useful messages. Is there something you would like unixclient -v to display, or is this more a documentation issue?

**Comment by tfarina** [comment]
I see now! I was not looking at the code. Now that I read it, does it make sense to clean up the usage() function and remove the options the are not available so it does not confuse the users like it confused me?

**Comment by bruceg** [comment]
I guess that's the question. The options do nothing, so the help text is obviously inaccurate. However, would printing something upon connecting be useful with -v?

**Comment by tfarina** [comment]
I don't think there is anything interesting print to the user when passing -v at this moment. At least I couldn't think in anything that would be helpful when enabling --verbose. Currently the server has an option -B to show a banner to the client, but the client does not handle that (but I think that is a case for another issue to be filed).

**Comment by bruceg** [comment]
The only thing I can think of as useful would be printing a message after connecting and before executing the program, the same as tcpclient -v does. Supporting -q may also be useful for completely disabling error messages.

**Comment by bruceg** [comment]
Fixed documentation in d126d7d5e66f884361220ae41f9e989ad7853989

**Comment by tfarina** [comment]
@bruceg thank you for fixing this! Really appreciated :)
